# Generated by Django 6.1 on 2026-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PestCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('pest_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=200)),
                ('start_month', models.IntegerField(help_text='1=Jan, 12=Dec')),
                ('end_month', models.IntegerField(help_text='1=Jan, 12=Dec')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('symptoms', models.TextField()),
                ('prevention_measures', models.TextField()),
                ('organic_controls', models.TextField(blank=True, default='')),
                ('chemical_controls', models.TextField(blank=True, default='')),
            ],
        ),
    ]
