# Generated by Django 6.1 on 2026-08-18 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leaf_scans/%Y/%m/%d/')),
                ('predicted_class', models.CharField(max_length=100)),
                ('disease_name', models.CharField(max_length=200)),
                ('crop', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('treatment_recommendation', models.TextField()),
                ('prevention_tips', models.TextField(blank=True, default='')),
                ('model_used', models.CharField(default='MobileNetV2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
