# Generated by Django 6.1 on 2026-08-18 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('soil_type', models.CharField(default='Loam', max_length=100)),
                ('growth_stage', models.CharField(default='Mid-Season (Flowering/Fruiting)', max_length=100)),
                ('field_area_m2', models.FloatField(default=1000.0)),
                ('soil_moisture_pct', models.FloatField(default=45.0)),
                ('eto_mm', models.FloatField(default=4.5)),
                ('kc_factor', models.FloatField(default=1.15)),
                ('etc_mm', models.FloatField(default=5.175)),
                ('effective_rainfall_mm', models.FloatField(default=0.0)),
                ('water_needed_liters_per_m2', models.FloatField()),
                ('total_water_liters', models.FloatField()),
                ('drip_irrigation_minutes', models.IntegerField(default=60)),
                ('recommended_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
