# Generated by Django 6.1 on 2026-08-18 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(default='Main Field A', max_length=100)),
                ('nitrogen', models.FloatField(help_text='Nitrogen N in mg/kg')),
                ('phosphorus', models.FloatField(help_text='Phosphorus P in mg/kg')),
                ('potassium', models.FloatField(help_text='Potassium K in mg/kg')),
                ('ph', models.FloatField(help_text='Soil pH level (0-14)')),
                ('moisture', models.FloatField(help_text='Soil Moisture percentage (0-100%)')),
                ('organic_carbon', models.FloatField(help_text='Organic Carbon percentage (0-3%)')),
                ('health_score', models.FloatField(default=85.0, help_text='Computed soil health score (0-100)')),
                ('recommendations', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
